 { ["../src/buffdets", "../src/uds", "../src/plotter","../src/qraph",
    "../src/pcore", "../src/pabi", "../src/ibap", "../src/qtransf", "../src/qutils", "../src/famdict", "../src/qijap", "../src/scarlet",
    "../src/fib","../src/gn"],
   [] }.

